from os import environ

SECRET_KEY = environ.get('SECRET_KEY')
DEBUG = environ.get('DEBUG')
ENV = environ.get('ENV')
APP_NAME = environ.get('APP_NAME')
MAIL_SERVER = environ.get('MAIL_SERVER')
MAIL_PORT = environ.get('MAIL_PORT')
MAIL_USE_TLS = environ.get('MAIL_USE_TLS')
MAIL_USE_SSL = environ.get('MAIL_USE_SSL')
MAIL_USERNAME = environ.get('MAIL_USERNAME')
MAIL_PASSWORD = environ.get('MAIL_PASSWORD')
MAIL_DEFAULT_SENDER = environ.get('MAIL_DEFAULT_SENDER')
RQ_QUEUES = environ.get('RQ_QUEUES')
SQLALCHEMY_DATABASE_URI = environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
MAIL_DEBUG = environ.get('MAIL_DEBUG')
